from .supir import NODE_CLASS_MAPPINGS as SUPIR_MAPPINGS
from .supir import NODE_DISPLAY_NAME_MAPPINGS as SUPIR_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(SUPIR_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(SUPIR_DISPLAY_MAPPINGS)
