"""
SEGS (Segmentation) nodes for modular image segment processing.
"""

from .query import NODE_CLASS_MAPPINGS as QUERY_MAPPINGS
from .query import NODE_DISPLAY_NAME_MAPPINGS as QUERY_DISPLAY_MAPPINGS
from .filter import NODE_CLASS_MAPPINGS as FILTER_MAPPINGS
from .filter import NODE_DISPLAY_NAME_MAPPINGS as FILTER_DISPLAY_MAPPINGS
from .decompose import NODE_CLASS_MAPPINGS as DECOMPOSE_MAPPINGS
from .decompose import NODE_DISPLAY_NAME_MAPPINGS as DECOMPOSE_DISPLAY_MAPPINGS
from .compose import NODE_CLASS_MAPPINGS as COMPOSE_MAPPINGS
from .compose import NODE_DISPLAY_NAME_MAPPINGS as COMPOSE_DISPLAY_MAPPINGS
from .wildcard import NODE_CLASS_MAPPINGS as WILDCARD_MAPPINGS
from .wildcard import NODE_DISPLAY_NAME_MAPPINGS as WILDCARD_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(QUERY_MAPPINGS)
NODE_CLASS_MAPPINGS.update(FILTER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DECOMPOSE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(COMPOSE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(WILDCARD_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(QUERY_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FILTER_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DECOMPOSE_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(COMPOSE_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WILDCARD_DISPLAY_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
