from .loaders import NODE_CLASS_MAPPINGS as LOADERS_MAPPINGS
from .loaders import NODE_DISPLAY_NAME_MAPPINGS as LOADERS_DISPLAY_MAPPINGS
from .info import NODE_CLASS_MAPPINGS as INFO_MAPPINGS
from .info import NODE_DISPLAY_NAME_MAPPINGS as INFO_DISPLAY_MAPPINGS
from .json import NODE_CLASS_MAPPINGS as JSON_MAPPINGS
from .json import NODE_DISPLAY_NAME_MAPPINGS as JSON_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOADERS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(INFO_MAPPINGS)
NODE_CLASS_MAPPINGS.update(JSON_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOADERS_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(INFO_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(JSON_DISPLAY_MAPPINGS)
